<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP360.Estoque.Application\ERP360.Estoque.Application.csproj" />
    <ProjectReference Include="..\ERP360.Estoque.Domain\ERP360.Estoque.Domain.csproj" />
  </ItemGroup>

</Project>
